Style/Encoding:
  Enabled: false

Style/Alias:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 60

Metrics/AbcSize:
  Max: 80

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10
  
Metrics/BlockLength:
  ExcludedMethods: ['describe']

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'spec/factory_spec.rb'
